version: '3.8'
services:
    database:
        container_name: mysql-laravel
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel_sample
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - '8606:3306'
        volumes:
            - ./database/mysql:/var/lib/mysql
    php:
        container_name: php-laravel
        build:
            context: ./php
        volumes:
            - ./src/laravel_sample:/var/www/laravel_sample
        depends_on:
            - database
    nginx:
        container_name: nginx-laravel
        image: nginx:stable-alpine
        ports:
            - '8600:80'
        volumes:
            - ./src/laravel_sample:/var/www/laravel_sample
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database
    phpmyadmin:
        container_name: phpmyadmin-laravel
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=password
            - UPLOAD_LIMIT=128M
        links:
            - database
        ports:
            - 8601:80
        volumes:
            - "./database/sessions:/sessions"
        depends_on:
            - nginx
            - php
            - database
